ir_version: 7
producer_name: "onnx-caffe2"
graph {
  node {
    input: "data_0"
    input: "conv1_w_0"
    input: "conv1_b_0"
    output: "conv1_1"
    op_type: "Conv"
    attribute {
      name: "strides"
      ints: 4
      ints: 4
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 11
      ints: 11
      type: INTS
    }
  }
  node {
    input: "conv1_1"
    output: "conv1_2"
    op_type: "Relu"
  }
  node {
    input: "conv1_2"
    output: "norm1_1"
    op_type: "LRN"
    attribute {
      name: "size"
      i: 5
      type: INT
    }
    attribute {
      name: "alpha"
      f: 0.0001
      type: FLOAT
    }
    attribute {
      name: "beta"
      f: 0.75
      type: FLOAT
    }
    attribute {
      name: "bias"
      f: 1.0
      type: FLOAT
    }
  }
  node {
    input: "norm1_1"
    output: "pool1_1"
    op_type: "MaxPool"
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
  }
  node {
    input: "pool1_1"
    input: "conv2_w_0"
    input: "conv2_b_0"
    output: "conv2_1"
    op_type: "Conv"
    attribute {
      name: "group"
      i: 2
      type: INT
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 2
      ints: 2
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 5
      ints: 5
      type: INTS
    }
  }
  node {
    input: "conv2_1"
    output: "conv2_2"
    op_type: "Relu"
  }
  node {
    input: "conv2_2"
    output: "norm2_1"
    op_type: "LRN"
    attribute {
      name: "size"
      i: 5
      type: INT
    }
    attribute {
      name: "alpha"
      f: 0.0001
      type: FLOAT
    }
    attribute {
      name: "beta"
      f: 0.75
      type: FLOAT
    }
    attribute {
      name: "bias"
      f: 1.0
      type: FLOAT
    }
  }
  node {
    input: "norm2_1"
    output: "pool2_1"
    op_type: "MaxPool"
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
  }
  node {
    input: "pool2_1"
    input: "conv3_w_0"
    input: "conv3_b_0"
    output: "conv3_1"
    op_type: "Conv"
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
  }
  node {
    input: "conv3_1"
    output: "conv3_2"
    op_type: "Relu"
  }
  node {
    input: "conv3_2"
    input: "conv4_w_0"
    input: "conv4_b_0"
    output: "conv4_1"
    op_type: "Conv"
    attribute {
      name: "group"
      i: 2
      type: INT
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
  }
  node {
    input: "conv4_1"
    output: "conv4_2"
    op_type: "Relu"
  }
  node {
    input: "conv4_2"
    input: "conv5_w_0"
    input: "conv5_b_0"
    output: "conv5_1"
    op_type: "Conv"
    attribute {
      name: "group"
      i: 2
      type: INT
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
  }
  node {
    input: "conv5_1"
    output: "conv5_2"
    op_type: "Relu"
  }
  node {
    input: "conv5_2"
    output: "pool5_1"
    op_type: "MaxPool"
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
  }
  node {
    input: "pool5_1"
    input: "OC2_DUMMY_1"
    output: "OC2_DUMMY_0"
    op_type: "Reshape"
  }
  node {
    input: "OC2_DUMMY_0"
    input: "fc6_w_0"
    input: "fc6_b_0"
    output: "fc6_1"
    op_type: "Gemm"
    attribute {
      name: "transB"
      i: 1
      type: INT
    }
  }
  node {
    input: "fc6_1"
    output: "fc6_2"
    op_type: "Relu"
  }
  node {
    input: "fc6_2"
    input: "46"
    output: "fc6_3"
    output: "_fc6_mask_1"
    op_type: "Dropout"
  }
  node {
    input: "fc6_3"
    input: "fc7_w_0"
    input: "fc7_b_0"
    output: "fc7_1"
    op_type: "Gemm"
    attribute {
      name: "transB"
      i: 1
      type: INT
    }
  }
  node {
    input: "fc7_1"
    output: "fc7_2"
    op_type: "Relu"
  }
  node {
    input: "fc7_2"
    input: "48"
    output: "fc7_3"
    output: "_fc7_mask_1"
    op_type: "Dropout"
  }
  node {
    input: "fc7_3"
    input: "fc8_w_0"
    input: "fc8_b_0"
    output: "fc8_1"
    op_type: "Gemm"
    attribute {
      name: "transB"
      i: 1
      type: INT
    }
  }
  node {
    input: "fc8_1"
    output: "prob_1"
    op_type: "Softmax"
  }
  name: "bvlc_alexnet"
  initializer {
    dims: 2
    data_type: 7
    name: "OC2_DUMMY_1"
    raw_data: "\001\000\000\000\000\000\000\000\000$\000\000\000\000\000\000"
  }
  initializer {
    data_type: 1
    float_data: 0.5
    name: "46"
  }
  initializer {
    data_type: 1
    float_data: 0.5
    name: "48"
  }
  input {
    name: "data_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 224
          }
          dim {
            dim_value: 224
          }
        }
      }
    }
  }
  input {
    name: "conv1_b_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 96
          }
        }
      }
    }
  }
  input {
    name: "conv1_w_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 96
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 11
          }
          dim {
            dim_value: 11
          }
        }
      }
    }
  }
  input {
    name: "conv2_b_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "conv2_w_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 48
          }
          dim {
            dim_value: 5
          }
          dim {
            dim_value: 5
          }
        }
      }
    }
  }
  input {
    name: "conv3_b_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 384
          }
        }
      }
    }
  }
  input {
    name: "conv3_w_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 384
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "conv4_b_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 384
          }
        }
      }
    }
  }
  input {
    name: "conv4_w_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 384
          }
          dim {
            dim_value: 192
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "conv5_b_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "conv5_w_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 192
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "fc6_b_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  input {
    name: "fc6_w_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 4096
          }
          dim {
            dim_value: 9216
          }
        }
      }
    }
  }
  input {
    name: "fc7_b_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  input {
    name: "fc7_w_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 4096
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  input {
    name: "fc8_b_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1000
          }
        }
      }
    }
  }
  input {
    name: "fc8_w_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1000
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  output {
    name: "prob_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1000
          }
        }
      }
    }
  }
  value_info {
    name: "OC2_DUMMY_1"
    type {
      tensor_type {
        elem_type: 7
        shape {
          dim {
            dim_value: 2
          }
        }
      }
    }
  }
  value_info {
    name: "46"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "48"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "conv1_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 96
          }
          dim {
            dim_value: 54
          }
          dim {
            dim_value: 54
          }
        }
      }
    }
  }
  value_info {
    name: "conv1_2"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 96
          }
          dim {
            dim_value: 54
          }
          dim {
            dim_value: 54
          }
        }
      }
    }
  }
  value_info {
    name: "norm1_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 96
          }
          dim {
            dim_value: 54
          }
          dim {
            dim_value: 54
          }
        }
      }
    }
  }
  value_info {
    name: "pool1_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 96
          }
          dim {
            dim_value: 26
          }
          dim {
            dim_value: 26
          }
        }
      }
    }
  }
  value_info {
    name: "conv2_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 26
          }
          dim {
            dim_value: 26
          }
        }
      }
    }
  }
  value_info {
    name: "conv2_2"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 26
          }
          dim {
            dim_value: 26
          }
        }
      }
    }
  }
  value_info {
    name: "norm2_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 26
          }
          dim {
            dim_value: 26
          }
        }
      }
    }
  }
  value_info {
    name: "pool2_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 12
          }
          dim {
            dim_value: 12
          }
        }
      }
    }
  }
  value_info {
    name: "conv3_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 384
          }
          dim {
            dim_value: 12
          }
          dim {
            dim_value: 12
          }
        }
      }
    }
  }
  value_info {
    name: "conv3_2"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 384
          }
          dim {
            dim_value: 12
          }
          dim {
            dim_value: 12
          }
        }
      }
    }
  }
  value_info {
    name: "conv4_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 384
          }
          dim {
            dim_value: 12
          }
          dim {
            dim_value: 12
          }
        }
      }
    }
  }
  value_info {
    name: "conv4_2"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 384
          }
          dim {
            dim_value: 12
          }
          dim {
            dim_value: 12
          }
        }
      }
    }
  }
  value_info {
    name: "conv5_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 12
          }
          dim {
            dim_value: 12
          }
        }
      }
    }
  }
  value_info {
    name: "conv5_2"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 12
          }
          dim {
            dim_value: 12
          }
        }
      }
    }
  }
  value_info {
    name: "pool5_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 6
          }
          dim {
            dim_value: 6
          }
        }
      }
    }
  }
  value_info {
    name: "OC2_DUMMY_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 9216
          }
        }
      }
    }
  }
  value_info {
    name: "fc6_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  value_info {
    name: "fc6_2"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  value_info {
    name: "fc6_3"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  value_info {
    name: "fc7_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  value_info {
    name: "fc7_2"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  value_info {
    name: "fc7_3"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  value_info {
    name: "fc8_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1000
          }
        }
      }
    }
  }
}
opset_import {
  domain: ""
  version: 12
}
