ir_version: 7
producer_name: "pytorch"
producer_version: "1.7"
graph {
  node {
    input: "input"
    output: "335"
    name: "Shape_0"
    op_type: "Shape"
  }
  node {
    output: "336"
    name: "Constant_1"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        data_type: 7
        raw_data: "\002\000\000\000\000\000\000\000"
      }
      type: TENSOR
    }
  }
  node {
    input: "335"
    input: "336"
    output: "337"
    name: "Gather_2"
    op_type: "Gather"
    attribute {
      name: "axis"
      i: 0
      type: INT
    }
  }
  node {
    input: "input"
    output: "338"
    name: "Shape_3"
    op_type: "Shape"
  }
  node {
    output: "339"
    name: "Constant_4"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        data_type: 7
        raw_data: "\003\000\000\000\000\000\000\000"
      }
      type: TENSOR
    }
  }
  node {
    input: "338"
    input: "339"
    output: "340"
    name: "Gather_5"
    op_type: "Gather"
    attribute {
      name: "axis"
      i: 0
      type: INT
    }
  }
  node {
    input: "input"
    input: "548"
    input: "549"
    output: "547"
    name: "Conv_6"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 7
      ints: 7
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 3
      ints: 3
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
  }
  node {
    input: "547"
    output: "343"
    name: "Relu_7"
    op_type: "Relu"
  }
  node {
    input: "343"
    output: "344"
    name: "MaxPool_8"
    op_type: "MaxPool"
    attribute {
      name: "ceil_mode"
      i: 0
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
  }
  node {
    input: "344"
    input: "551"
    input: "552"
    output: "550"
    name: "Conv_9"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "550"
    output: "347"
    name: "Relu_10"
    op_type: "Relu"
  }
  node {
    input: "347"
    input: "554"
    input: "555"
    output: "553"
    name: "Conv_11"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "553"
    output: "350"
    name: "Relu_12"
    op_type: "Relu"
  }
  node {
    input: "350"
    input: "557"
    input: "558"
    output: "556"
    name: "Conv_13"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "344"
    input: "560"
    input: "561"
    output: "559"
    name: "Conv_14"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "556"
    input: "559"
    output: "355"
    name: "Add_15"
    op_type: "Add"
  }
  node {
    input: "355"
    output: "356"
    name: "Relu_16"
    op_type: "Relu"
  }
  node {
    input: "356"
    input: "563"
    input: "564"
    output: "562"
    name: "Conv_17"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "562"
    output: "359"
    name: "Relu_18"
    op_type: "Relu"
  }
  node {
    input: "359"
    input: "566"
    input: "567"
    output: "565"
    name: "Conv_19"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "565"
    output: "362"
    name: "Relu_20"
    op_type: "Relu"
  }
  node {
    input: "362"
    input: "569"
    input: "570"
    output: "568"
    name: "Conv_21"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "568"
    input: "356"
    output: "365"
    name: "Add_22"
    op_type: "Add"
  }
  node {
    input: "365"
    output: "366"
    name: "Relu_23"
    op_type: "Relu"
  }
  node {
    input: "366"
    input: "572"
    input: "573"
    output: "571"
    name: "Conv_24"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "571"
    output: "369"
    name: "Relu_25"
    op_type: "Relu"
  }
  node {
    input: "369"
    input: "575"
    input: "576"
    output: "574"
    name: "Conv_26"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "574"
    output: "372"
    name: "Relu_27"
    op_type: "Relu"
  }
  node {
    input: "372"
    input: "578"
    input: "579"
    output: "577"
    name: "Conv_28"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "577"
    input: "366"
    output: "375"
    name: "Add_29"
    op_type: "Add"
  }
  node {
    input: "375"
    output: "376"
    name: "Relu_30"
    op_type: "Relu"
  }
  node {
    input: "376"
    input: "581"
    input: "582"
    output: "580"
    name: "Conv_31"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "580"
    output: "379"
    name: "Relu_32"
    op_type: "Relu"
  }
  node {
    input: "379"
    input: "584"
    input: "585"
    output: "583"
    name: "Conv_33"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
  }
  node {
    input: "583"
    output: "382"
    name: "Relu_34"
    op_type: "Relu"
  }
  node {
    input: "382"
    input: "587"
    input: "588"
    output: "586"
    name: "Conv_35"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "376"
    input: "590"
    input: "591"
    output: "589"
    name: "Conv_36"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
  }
  node {
    input: "586"
    input: "589"
    output: "387"
    name: "Add_37"
    op_type: "Add"
  }
  node {
    input: "387"
    output: "388"
    name: "Relu_38"
    op_type: "Relu"
  }
  node {
    input: "388"
    input: "593"
    input: "594"
    output: "592"
    name: "Conv_39"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "592"
    output: "391"
    name: "Relu_40"
    op_type: "Relu"
  }
  node {
    input: "391"
    input: "596"
    input: "597"
    output: "595"
    name: "Conv_41"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "595"
    output: "394"
    name: "Relu_42"
    op_type: "Relu"
  }
  node {
    input: "394"
    input: "599"
    input: "600"
    output: "598"
    name: "Conv_43"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "598"
    input: "388"
    output: "397"
    name: "Add_44"
    op_type: "Add"
  }
  node {
    input: "397"
    output: "398"
    name: "Relu_45"
    op_type: "Relu"
  }
  node {
    input: "398"
    input: "602"
    input: "603"
    output: "601"
    name: "Conv_46"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "601"
    output: "401"
    name: "Relu_47"
    op_type: "Relu"
  }
  node {
    input: "401"
    input: "605"
    input: "606"
    output: "604"
    name: "Conv_48"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "604"
    output: "404"
    name: "Relu_49"
    op_type: "Relu"
  }
  node {
    input: "404"
    input: "608"
    input: "609"
    output: "607"
    name: "Conv_50"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "607"
    input: "398"
    output: "407"
    name: "Add_51"
    op_type: "Add"
  }
  node {
    input: "407"
    output: "408"
    name: "Relu_52"
    op_type: "Relu"
  }
  node {
    input: "408"
    input: "611"
    input: "612"
    output: "610"
    name: "Conv_53"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "610"
    output: "411"
    name: "Relu_54"
    op_type: "Relu"
  }
  node {
    input: "411"
    input: "614"
    input: "615"
    output: "613"
    name: "Conv_55"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "613"
    output: "414"
    name: "Relu_56"
    op_type: "Relu"
  }
  node {
    input: "414"
    input: "617"
    input: "618"
    output: "616"
    name: "Conv_57"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "616"
    input: "408"
    output: "417"
    name: "Add_58"
    op_type: "Add"
  }
  node {
    input: "417"
    output: "418"
    name: "Relu_59"
    op_type: "Relu"
  }
  node {
    input: "418"
    input: "620"
    input: "621"
    output: "619"
    name: "Conv_60"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "619"
    output: "421"
    name: "Relu_61"
    op_type: "Relu"
  }
  node {
    input: "421"
    input: "623"
    input: "624"
    output: "622"
    name: "Conv_62"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "622"
    output: "424"
    name: "Relu_63"
    op_type: "Relu"
  }
  node {
    input: "424"
    input: "626"
    input: "627"
    output: "625"
    name: "Conv_64"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "418"
    input: "629"
    input: "630"
    output: "628"
    name: "Conv_65"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "625"
    input: "628"
    output: "429"
    name: "Add_66"
    op_type: "Add"
  }
  node {
    input: "429"
    output: "430"
    name: "Relu_67"
    op_type: "Relu"
  }
  node {
    input: "430"
    input: "632"
    input: "633"
    output: "631"
    name: "Conv_68"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "631"
    output: "433"
    name: "Relu_69"
    op_type: "Relu"
  }
  node {
    input: "433"
    input: "635"
    input: "636"
    output: "634"
    name: "Conv_70"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 2
      ints: 2
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "634"
    output: "436"
    name: "Relu_71"
    op_type: "Relu"
  }
  node {
    input: "436"
    input: "638"
    input: "639"
    output: "637"
    name: "Conv_72"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "637"
    input: "430"
    output: "439"
    name: "Add_73"
    op_type: "Add"
  }
  node {
    input: "439"
    output: "440"
    name: "Relu_74"
    op_type: "Relu"
  }
  node {
    input: "440"
    input: "641"
    input: "642"
    output: "640"
    name: "Conv_75"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "640"
    output: "443"
    name: "Relu_76"
    op_type: "Relu"
  }
  node {
    input: "443"
    input: "644"
    input: "645"
    output: "643"
    name: "Conv_77"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 2
      ints: 2
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "643"
    output: "446"
    name: "Relu_78"
    op_type: "Relu"
  }
  node {
    input: "446"
    input: "647"
    input: "648"
    output: "646"
    name: "Conv_79"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "646"
    input: "440"
    output: "449"
    name: "Add_80"
    op_type: "Add"
  }
  node {
    input: "449"
    output: "450"
    name: "Relu_81"
    op_type: "Relu"
  }
  node {
    input: "450"
    input: "650"
    input: "651"
    output: "649"
    name: "Conv_82"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "649"
    output: "453"
    name: "Relu_83"
    op_type: "Relu"
  }
  node {
    input: "453"
    input: "653"
    input: "654"
    output: "652"
    name: "Conv_84"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 2
      ints: 2
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "652"
    output: "456"
    name: "Relu_85"
    op_type: "Relu"
  }
  node {
    input: "456"
    input: "656"
    input: "657"
    output: "655"
    name: "Conv_86"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "655"
    input: "450"
    output: "459"
    name: "Add_87"
    op_type: "Add"
  }
  node {
    input: "459"
    output: "460"
    name: "Relu_88"
    op_type: "Relu"
  }
  node {
    input: "460"
    input: "659"
    input: "660"
    output: "658"
    name: "Conv_89"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "658"
    output: "463"
    name: "Relu_90"
    op_type: "Relu"
  }
  node {
    input: "463"
    input: "662"
    input: "663"
    output: "661"
    name: "Conv_91"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 2
      ints: 2
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "661"
    output: "466"
    name: "Relu_92"
    op_type: "Relu"
  }
  node {
    input: "466"
    input: "665"
    input: "666"
    output: "664"
    name: "Conv_93"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "664"
    input: "460"
    output: "469"
    name: "Add_94"
    op_type: "Add"
  }
  node {
    input: "469"
    output: "470"
    name: "Relu_95"
    op_type: "Relu"
  }
  node {
    input: "470"
    input: "668"
    input: "669"
    output: "667"
    name: "Conv_96"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "667"
    output: "473"
    name: "Relu_97"
    op_type: "Relu"
  }
  node {
    input: "473"
    input: "671"
    input: "672"
    output: "670"
    name: "Conv_98"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 2
      ints: 2
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "670"
    output: "476"
    name: "Relu_99"
    op_type: "Relu"
  }
  node {
    input: "476"
    input: "674"
    input: "675"
    output: "673"
    name: "Conv_100"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "673"
    input: "470"
    output: "479"
    name: "Add_101"
    op_type: "Add"
  }
  node {
    input: "479"
    output: "480"
    name: "Relu_102"
    op_type: "Relu"
  }
  node {
    input: "480"
    input: "677"
    input: "678"
    output: "676"
    name: "Conv_103"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "676"
    output: "483"
    name: "Relu_104"
    op_type: "Relu"
  }
  node {
    input: "483"
    input: "680"
    input: "681"
    output: "679"
    name: "Conv_105"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 2
      ints: 2
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "679"
    output: "486"
    name: "Relu_106"
    op_type: "Relu"
  }
  node {
    input: "486"
    input: "683"
    input: "684"
    output: "682"
    name: "Conv_107"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "480"
    input: "686"
    input: "687"
    output: "685"
    name: "Conv_108"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "682"
    input: "685"
    output: "491"
    name: "Add_109"
    op_type: "Add"
  }
  node {
    input: "491"
    output: "492"
    name: "Relu_110"
    op_type: "Relu"
  }
  node {
    input: "492"
    input: "689"
    input: "690"
    output: "688"
    name: "Conv_111"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "688"
    output: "495"
    name: "Relu_112"
    op_type: "Relu"
  }
  node {
    input: "495"
    input: "692"
    input: "693"
    output: "691"
    name: "Conv_113"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 4
      ints: 4
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 4
      ints: 4
      ints: 4
      ints: 4
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "691"
    output: "498"
    name: "Relu_114"
    op_type: "Relu"
  }
  node {
    input: "498"
    input: "695"
    input: "696"
    output: "694"
    name: "Conv_115"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "694"
    input: "492"
    output: "501"
    name: "Add_116"
    op_type: "Add"
  }
  node {
    input: "501"
    output: "502"
    name: "Relu_117"
    op_type: "Relu"
  }
  node {
    input: "502"
    input: "698"
    input: "699"
    output: "697"
    name: "Conv_118"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "697"
    output: "505"
    name: "Relu_119"
    op_type: "Relu"
  }
  node {
    input: "505"
    input: "701"
    input: "702"
    output: "700"
    name: "Conv_120"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 4
      ints: 4
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 4
      ints: 4
      ints: 4
      ints: 4
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "700"
    output: "508"
    name: "Relu_121"
    op_type: "Relu"
  }
  node {
    input: "508"
    input: "704"
    input: "705"
    output: "703"
    name: "Conv_122"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "703"
    input: "502"
    output: "511"
    name: "Add_123"
    op_type: "Add"
  }
  node {
    input: "511"
    output: "512"
    name: "Relu_124"
    op_type: "Relu"
  }
  node {
    input: "512"
    input: "707"
    input: "708"
    output: "706"
    name: "Conv_125"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "706"
    output: "515"
    name: "Relu_126"
    op_type: "Relu"
  }
  node {
    input: "515"
    input: "classifier.4.weight"
    input: "classifier.4.bias"
    output: "516"
    name: "Conv_127"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "337"
    output: "517"
    name: "Unsqueeze_128"
    op_type: "Unsqueeze"
    attribute {
      name: "axes"
      ints: 0
      type: INTS
    }
  }
  node {
    input: "340"
    output: "518"
    name: "Unsqueeze_129"
    op_type: "Unsqueeze"
    attribute {
      name: "axes"
      ints: 0
      type: INTS
    }
  }
  node {
    input: "517"
    input: "518"
    output: "519"
    name: "Concat_130"
    op_type: "Concat"
    attribute {
      name: "axis"
      i: 0
      type: INT
    }
  }
  node {
    output: "520"
    name: "Constant_131"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 0
        data_type: 1
        raw_data: ""
      }
      type: TENSOR
    }
  }
  node {
    input: "516"
    output: "521"
    name: "Shape_132"
    op_type: "Shape"
  }
  node {
    output: "522"
    name: "Constant_133"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 1
        data_type: 7
        raw_data: "\000\000\000\000\000\000\000\000"
      }
      type: TENSOR
    }
  }
  node {
    output: "523"
    name: "Constant_134"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 1
        data_type: 7
        raw_data: "\000\000\000\000\000\000\000\000"
      }
      type: TENSOR
    }
  }
  node {
    output: "524"
    name: "Constant_135"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 1
        data_type: 7
        raw_data: "\002\000\000\000\000\000\000\000"
      }
      type: TENSOR
    }
  }
  node {
    input: "521"
    input: "523"
    input: "524"
    input: "522"
    output: "525"
    name: "Slice_136"
    op_type: "Slice"
  }
  node {
    input: "519"
    output: "526"
    name: "Cast_137"
    op_type: "Cast"
    attribute {
      name: "to"
      i: 7
      type: INT
    }
  }
  node {
    input: "525"
    input: "526"
    output: "527"
    name: "Concat_138"
    op_type: "Concat"
    attribute {
      name: "axis"
      i: 0
      type: INT
    }
  }
  node {
    output: "528"
    name: "Constant_139"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 0
        data_type: 1
        raw_data: ""
      }
      type: TENSOR
    }
  }
  node {
    input: "516"
    input: "520"
    input: "528"
    input: "527"
    output: "out"
    name: "Resize_140"
    op_type: "Resize"
    attribute {
      name: "coordinate_transformation_mode"
      s: "pytorch_half_pixel"
      type: STRING
    }
    attribute {
      name: "cubic_coeff_a"
      f: -0.75
      type: FLOAT
    }
    attribute {
      name: "mode"
      s: "linear"
      type: STRING
    }
    attribute {
      name: "nearest_mode"
      s: "floor"
      type: STRING
    }
  }
  node {
    input: "480"
    input: "710"
    input: "711"
    output: "709"
    name: "Conv_141"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "709"
    output: "532"
    name: "Relu_142"
    op_type: "Relu"
  }
  node {
    input: "532"
    input: "aux_classifier.4.weight"
    input: "aux_classifier.4.bias"
    output: "533"
    name: "Conv_143"
    op_type: "Conv"
    attribute {
      name: "dilations"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "group"
      i: 1
      type: INT
    }
    attribute {
      name: "kernel_shape"
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "337"
    output: "534"
    name: "Unsqueeze_144"
    op_type: "Unsqueeze"
    attribute {
      name: "axes"
      ints: 0
      type: INTS
    }
  }
  node {
    input: "340"
    output: "535"
    name: "Unsqueeze_145"
    op_type: "Unsqueeze"
    attribute {
      name: "axes"
      ints: 0
      type: INTS
    }
  }
  node {
    input: "534"
    input: "535"
    output: "536"
    name: "Concat_146"
    op_type: "Concat"
    attribute {
      name: "axis"
      i: 0
      type: INT
    }
  }
  node {
    output: "537"
    name: "Constant_147"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 0
        data_type: 1
        raw_data: ""
      }
      type: TENSOR
    }
  }
  node {
    input: "533"
    output: "538"
    name: "Shape_148"
    op_type: "Shape"
  }
  node {
    output: "539"
    name: "Constant_149"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 1
        data_type: 7
        raw_data: "\000\000\000\000\000\000\000\000"
      }
      type: TENSOR
    }
  }
  node {
    output: "540"
    name: "Constant_150"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 1
        data_type: 7
        raw_data: "\000\000\000\000\000\000\000\000"
      }
      type: TENSOR
    }
  }
  node {
    output: "541"
    name: "Constant_151"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 1
        data_type: 7
        raw_data: "\002\000\000\000\000\000\000\000"
      }
      type: TENSOR
    }
  }
  node {
    input: "538"
    input: "540"
    input: "541"
    input: "539"
    output: "542"
    name: "Slice_152"
    op_type: "Slice"
  }
  node {
    input: "536"
    output: "543"
    name: "Cast_153"
    op_type: "Cast"
    attribute {
      name: "to"
      i: 7
      type: INT
    }
  }
  node {
    input: "542"
    input: "543"
    output: "544"
    name: "Concat_154"
    op_type: "Concat"
    attribute {
      name: "axis"
      i: 0
      type: INT
    }
  }
  node {
    output: "545"
    name: "Constant_155"
    op_type: "Constant"
    attribute {
      name: "value"
      t {
        dims: 0
        data_type: 1
        raw_data: ""
      }
      type: TENSOR
    }
  }
  node {
    input: "533"
    input: "537"
    input: "545"
    input: "544"
    output: "aux"
    name: "Resize_156"
    op_type: "Resize"
    attribute {
      name: "coordinate_transformation_mode"
      s: "pytorch_half_pixel"
      type: STRING
    }
    attribute {
      name: "cubic_coeff_a"
      f: -0.75
      type: FLOAT
    }
    attribute {
      name: "mode"
      s: "linear"
      type: STRING
    }
    attribute {
      name: "nearest_mode"
      s: "floor"
      type: STRING
    }
  }
  name: "torch-jit-export"
  initializer {
    dims: 64
    data_type: 1
    name: "549"
    raw_data: "o\236\002>#\347\272>\333\010\220\275E\304\331=t\271\031>\214\343\370=\351\261\025>L\251\023>yG#>\345Q\004>_\300\276=\264\022\025\276\222f\330=\2524\207\262\251\236;>\2751\027>\373h\307>\246S\032>`R\'>\nz\267>\351\366+>\177\270\020>\213\372\031>]\347\262>\264\376\027>y\\\355>Zw#>9\232&>\234\\\353=N\323B>\030\272\320=&\243]=M\250\032?\274\037->\036\2530>\245 \301>\021\300\356=\357\004\004>\326x\031>\024\322!>\262l\'?\345^(>\224\'\215\276\366M\036?0?\303\276\024\247\022>\342d0>\372\276\231>P;p\276 a5>\336\324\036>M\037\320=\266\361\006\2777\261\007>u\227\014>\3062h>\304T\234>\316\346\371\275\034T\240\276h\2242\274\261\010\366=\361\316!>\341w\025?\324\035\035>"
  }
  initializer {
    dims: 64
    data_type: 1
    name: "552"
    raw_data: "n\305*?l)\220>|2\321\276\320\212\250>\276\345\247>^\221%>\032\007\226>\344\335-\26375\351\276\013u>>Z\232\223>\341\326\203\276\332\032U>\315\275\231>w\353\327>\'3I>HM\300>\257i_\276\206\020Z>\032\201\225>\010K\025>\356y\203\275\204\242b>\261\242\342\262>\362\261>\370\212b>\244\004a>\300\020\336\262\226\315 >\275\342\310>\nc\210>\016 \360\276\324\310B\275\200\267T\275@\340\220>l\372n>\007p\246>2\003\373=\311\247\034>\020\'\231\275\307\343\212>`\"\027\275\210\340\210>\277\376\315>\235\265~>\363mt>\327\276\232>\377\036!?\314\005\"<\246_\245>\014\2723>\022\031\177>Bk\'\276\332;\376>!\3777\276\350\212\346>\366\000\005\263v=\213>\222\236\021\263\310Q\255\276jd\334\275\243\307\004\276E\332\244>\300\225\033?"
  }
  initializer {
    dims: 64
    data_type: 1
    name: "555"
    raw_data: "\265\302H\263\004\023\276\274>zv>\231\2349>gmj>\243\331\206>\261\243)>%\224\271=\204\0360\276T\342\363\275\275\336\233<\364\035%>w^^>N\177\243\2758$\010\276\033\035H>\337\327\263>i\022\216\275]>\224>\354\254\030\265\213\324\005\276U\3535>\002\362T\275(\017\032>&\203E\275P<\352\274#a\355\276 \202\202\276\261\254\306=\311\321.\276\345\335\347=d\n\035>\203Gg>\342Y\335>\302O\246=/,:>\355\215x>\351\257\261=\\\017\003\275h\320\"\276\031\237\206>T\303\322\275\352yb\275\262\223\n>\366\252\201\276 \272a\276\361\032\010>\t\274h?E\202\206>\313\023\335=\253\371\201>\334f+=\314\027q\276\376\2632>\312\314Y>\"\327\301=\211oo?%\220\265\274A\237\354\275P(\037\273*e\225<HV\242\262\026\351\263\276\340L\326\275"
  }
  initializer {
    dims: 64
    data_type: 1
    name: "564"
    raw_data: "\321!\221<\316S\224\276vD\267\275\311\223\315\275\364\343\241\276\031\205\r\275\370\205\004\276\022\016\232\275\231!\033>Fq,\277$\216\203>\341\360\214\276A\002D\275j\006\036\263z\003\316=\\S\014\276p\235\013\274\343\177?<q\333\025\276\031\204\201\276\206\257-=\275\374\013>\362\314\210=\tfa\275\334\024\234=lF\200\275\272\207I=+#\274>\272s\241\275{rH\276\010\243z\276s\353\017\275I\270\271\276\272\333\031\276\246f\236\274\320\342\351\275\233\336\211>\223|$\276\326\227\270\275\256\2131=\314\025\230\276\266\202\206\275Wu\251\275\212\312\204\276.\263\210>\252\327p\265\310o|> \0200\263\352\215\333<@\253\312;\nl*\276\202\314L\276\314<\256>\266R\036\276\303Aw>\240\211\023\274\024\342\317\262\360\301\031\276x\371\264>x\n\\\274\375\002\030\275\026\204g>\376\357`\276W\'^<"
  }
  initializer {
    dims: 64
    data_type: 1
    name: "567"
    raw_data: "\236\220\246>4\"6=\274\270D<\371\274\023>\363\016\374\275\240\264i>I\356\010\275\326?\033>\336\003z>\307\314\030>\361]\351=\317\204]\275\266\240\371\275\212\026k\275\037\023@>\020^\026\274\220\362\027=g\377\032\276\214R\261>X\271f<\355\356,<\000Wq=\322y\376=\360a+\275\267\363->\027W\270\276\032\246\215>\263\2170\276*\023\210>\274\266\025>\226Y\270\275\220\214\030\275(Z\253\273\377`\340=\350x\372<\034\312\200<4\234k>\236\307\257\275#\221\214=Fd\032\275\240\321\211\275\220~\372=ueT\276\207\324\251>\340\271\205<\363\342\016=\000\022\250\273\\\217#=X\343{;,\n7\274/H\213=\317\212\341=0\214\356>\246@\346\275\256\364\220>wr@=\r\2158>:\200\341=\034\020\217\276\370\030\362=&\204}=\366\310\341= \006\014\273(H\352="
  }
  initializer {
    dims: 64
    data_type: 1
    name: "573"
    raw_data: "\275\010L\275J\214\366<(\002\226\274@\261\321\274\030\366k\276\"w\221\275(\246\325\274)\324\254=\323\260/>\326\235\332=\034\'\371\275\006\246\221\276\345\217\275=*<\245\275\344yk\275lJ\353\274\204Pg?w\ny= \334;\274\206`\316\275\2221\364\275\201\210\225=@\344l=\230\203\215\274\215\334\276<\264\241\n\276\254\345)=\037\357\'<\3449\250<\367\275\242\275\243\227\213\275\362+\351\275\310\233\324=0F5\273|\2460\275\334F\252\275`\273S>\275\212+\275\362\232\242;\351\310>\276\004\335\377<\205\372\017=\004%\327=\0349\325\275\242\351{<\337\200W\276\006\304\035=\200\311\"\271\261L\234>gW\241\275\304w\274\274[\266\245=\255\216\251\275+\006\024>\032\307\006\276P\373\254\2756\373L\275\264\263\303=A:\217>=\032\307\275\020\266\344;\274\362\264=\200)\214<\346\212\315\274"
  }
  initializer {
    dims: 64
    data_type: 1
    name: "576"
    raw_data: "\363P\304<x\262h\275\223/\r=^\270\202\275\017H\244=\000\222H\272\034\000)=09\016>\224\030G=@\246\313\275&\343\242\275\036\203\327=\220\0164\275\202\276+\275\350\227\372\2748v\002\274\276\304C\275\"Pz=\362\002\223\275\317P\263\275P\274\202;\nA\033>\325#K\274{\326\037\275\353\367\250=\232N\027=a\2724=k\242\021=\314O\326\275\310\374\303<\372ka=\032,;\275\260e\350=\375\306\311\275\300S\021=\017\224\256=\002\320/>,\013\221=W\374?>\354\337\301<\242&\361\274\276K2>H\205H\276\336\245\256<\364\366\306\273\376\334S\275\010\037\032\274\230\307!<\\\232\271\275\216M\265=\331e\013\275\020\226U\275\0243\267\273\360 \334;\204;1\275\370f\221\275\300\251\037::p%\276w\212\223=u\204\364=\326\033\367\276\376\rz\274\020\254\221\273\372\324C="
  }
  initializer {
    dims: 21
    data_type: 1
    name: "aux_classifier.4.bias"
    raw_data: "\013;O?\223\252\020\276\022s\014\276\254\277\216\275\301#\332\275\325\302\351\275P\367\212\275+\'#=r\201\207\275\302\264\232\275`\002\260\275W\204\203>D\246\010=\2061\266\275\226\343\000\2755y\202>\274TF\275EX0\276\355\372f\275\251w\224\274\223r\352\275"
  }
  initializer {
    dims: 21
    data_type: 1
    name: "classifier.4.bias"
    raw_data: "\227\'P?QA\326\275\342\330\233\275X\261\256\275\266^\335\275\275\246\234\275%\220\237\275\201\301\205<\037A.\275#jz\275~\247\204\275j\267\200>\230\243x\274^\352\225\275q0\272\275\342\373\311=k\270\017\275\241m\336\275Y&\240\275A,x\275\007a\252\275"
  }
  input {
    name: "input"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_param: "batch"
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_param: "height"
          }
          dim {
            dim_param: "width"
          }
        }
      }
    }
  }
  input {
    name: "548"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 7
          }
          dim {
            dim_value: 7
          }
        }
      }
    }
  }
  input {
    name: "551"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "554"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "557"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "558"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "560"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "561"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "563"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "566"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "569"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "570"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "572"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "575"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "578"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 64
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "579"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "581"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "582"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
        }
      }
    }
  }
  input {
    name: "584"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "585"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
        }
      }
    }
  }
  input {
    name: "587"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "588"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "590"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "591"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "593"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "594"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
        }
      }
    }
  }
  input {
    name: "596"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "597"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
        }
      }
    }
  }
  input {
    name: "599"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "600"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "602"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "603"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
        }
      }
    }
  }
  input {
    name: "605"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "606"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
        }
      }
    }
  }
  input {
    name: "608"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "609"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "611"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "612"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
        }
      }
    }
  }
  input {
    name: "614"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "615"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 128
          }
        }
      }
    }
  }
  input {
    name: "617"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 128
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "618"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "620"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "621"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "623"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "624"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "626"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "627"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  input {
    name: "629"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "630"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  input {
    name: "632"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "633"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "635"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "636"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "638"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "639"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  input {
    name: "641"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "642"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "644"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "645"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "647"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "648"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  input {
    name: "650"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "651"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "653"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "654"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "656"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "657"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  input {
    name: "659"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "660"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "662"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "663"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "665"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "666"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  input {
    name: "668"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "669"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "671"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "672"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "674"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "675"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  input {
    name: "677"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "678"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "680"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "681"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "683"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 2048
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "684"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 2048
          }
        }
      }
    }
  }
  input {
    name: "686"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 2048
          }
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "687"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 2048
          }
        }
      }
    }
  }
  input {
    name: "689"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 2048
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "690"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "692"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "693"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "695"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 2048
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "696"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 2048
          }
        }
      }
    }
  }
  input {
    name: "698"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 2048
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "699"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "701"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "702"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "704"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 2048
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "705"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 2048
          }
        }
      }
    }
  }
  input {
    name: "707"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 2048
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "708"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "710"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "711"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "aux_classifier.4.weight"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 21
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  input {
    name: "classifier.4.weight"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 21
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  output {
    name: "out"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_param: "batch"
          }
          dim {
            dim_value: 21
          }
          dim {
            dim_param: "height"
          }
          dim {
            dim_param: "width"
          }
        }
      }
    }
  }
  output {
    name: "aux"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_param: "batch"
          }
          dim {
            dim_value: 21
          }
          dim {
            dim_param: "height"
          }
          dim {
            dim_param: "width"
          }
        }
      }
    }
  }
  value_info {
    name: "549"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
        }
      }
    }
  }
  value_info {
    name: "552"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
        }
      }
    }
  }
  value_info {
    name: "555"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
        }
      }
    }
  }
  value_info {
    name: "564"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
        }
      }
    }
  }
  value_info {
    name: "567"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
        }
      }
    }
  }
  value_info {
    name: "573"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
        }
      }
    }
  }
  value_info {
    name: "576"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 64
          }
        }
      }
    }
  }
  value_info {
    name: "aux_classifier.4.bias"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 21
          }
        }
      }
    }
  }
  value_info {
    name: "classifier.4.bias"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 21
          }
        }
      }
    }
  }
}
opset_import {
  domain: ""
  version: 12
}
