ir_version: 7
producer_name: "onnx.quantize"
producer_version: "0.1.0"
graph {
  node {
    input: "gpu_0/data_0"
    input: "gpu_0/data_0_scale"
    input: "gpu_0/data_0_zero_point"
    output: "gpu_0/data_0_quantized"
    name: "gpu_0/data_0_Conv_nc_rename_0_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/conv1_b_0_quantized"
    input: "gpu_0/conv1_b_0_scale"
    input: "gpu_0/conv1_b_0_zero_point"
    output: "gpu_0/conv1_b_0_dequantized"
    name: "gpu_0/conv1_b_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv1_w_0_quantized"
    input: "gpu_0/conv1_w_0_scale"
    input: "gpu_0/conv1_w_0_zero_point"
    output: "gpu_0/conv1_w_0_dequantized"
    name: "gpu_0/conv1_w_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/data_0_quantized"
    input: "gpu_0/data_0_scale"
    input: "gpu_0/data_0_zero_point"
    output: "gpu_0/data_0_dequantized"
    name: "gpu_0/data_0_Conv_nc_rename_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/data_0_dequantized"
    input: "gpu_0/conv1_w_0_dequantized"
    input: "gpu_0/conv1_b_0_dequantized"
    output: "gpu_0/conv1_1_QuantizeInput"
    name: "Conv_nc_rename_0_quant"
    op_type: "Conv"
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 7
      ints: 7
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
  }
  node {
    input: "gpu_0/conv1_1_QuantizeInput"
    input: "gpu_0/conv1_1_scale"
    input: "gpu_0/conv1_1_zero_point"
    output: "gpu_0/conv1_1_quantized"
    name: "gpu_0/conv1_1_Conv_nc_rename_0_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/conv1_1_quantized"
    input: "gpu_0/conv1_1_scale"
    input: "gpu_0/conv1_1_zero_point"
    output: "gpu_0/conv1_1"
    name: "gpu_0/conv1_1_Conv_nc_rename_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv1_1"
    output: "gpu_0/norm1_1"
    name: "LRN_nc_rename_2"
    op_type: "LRN"
    attribute {
      name: "beta"
      f: 0.75
      type: FLOAT
    }
    attribute {
      name: "bias"
      f: 2.0
      type: FLOAT
    }
    attribute {
      name: "alpha"
      f: 0.0005
      type: FLOAT
    }
    attribute {
      name: "size"
      i: 5
      type: INT
    }
  }
  node {
    input: "gpu_0/norm1_1"
    output: "gpu_0/pool1_1"
    name: "MaxPool_nc_rename_3"
    op_type: "MaxPool"
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
  }
  node {
    input: "gpu_0/pool1_1"
    input: "gpu_0/pool1_1_scale"
    input: "gpu_0/pool1_1_zero_point"
    output: "gpu_0/pool1_1_Conv_nc_rename_4_QuantizeLinear"
    name: "gpu_0/pool1_1_Conv_nc_rename_4_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/conv2_b_0_quantized"
    input: "gpu_0/conv2_b_0_scale"
    input: "gpu_0/conv2_b_0_zero_point"
    output: "gpu_0/conv2_b_0_dequantized"
    name: "gpu_0/conv2_b_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv2_w_0_quantized"
    input: "gpu_0/conv2_w_0_scale"
    input: "gpu_0/conv2_w_0_zero_point"
    output: "gpu_0/conv2_w_0_dequantized"
    name: "gpu_0/conv2_w_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/pool1_1_Conv_nc_rename_4_QuantizeLinear"
    input: "gpu_0/pool1_1_scale"
    input: "gpu_0/pool1_1_zero_point"
    output: "gpu_0/pool1_1_Conv_nc_rename_4_dequantized"
    name: "gpu_0/pool1_1_Conv_nc_rename_4_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/pool1_1_Conv_nc_rename_4_dequantized"
    input: "gpu_0/conv2_w_0_dequantized"
    input: "gpu_0/conv2_b_0_dequantized"
    output: "gpu_0/conv2_1_QuantizeInput"
    name: "Conv_nc_rename_4_quant"
    op_type: "Conv"
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 5
      ints: 5
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
  }
  node {
    input: "gpu_0/conv2_1_QuantizeInput"
    input: "gpu_0/conv2_1_scale"
    input: "gpu_0/conv2_1_zero_point"
    output: "gpu_0/conv2_1_quantized"
    name: "gpu_0/conv2_1_Conv_nc_rename_4_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/conv2_1_quantized"
    input: "gpu_0/conv2_1_scale"
    input: "gpu_0/conv2_1_zero_point"
    output: "gpu_0/conv2_1"
    name: "gpu_0/conv2_1_Conv_nc_rename_4_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv2_1"
    output: "gpu_0/norm2_1"
    name: "LRN_nc_rename_6"
    op_type: "LRN"
    attribute {
      name: "beta"
      f: 0.75
      type: FLOAT
    }
    attribute {
      name: "bias"
      f: 2.0
      type: FLOAT
    }
    attribute {
      name: "alpha"
      f: 0.0005
      type: FLOAT
    }
    attribute {
      name: "size"
      i: 5
      type: INT
    }
  }
  node {
    input: "gpu_0/norm2_1"
    output: "gpu_0/pool2_1"
    name: "MaxPool_nc_rename_7"
    op_type: "MaxPool"
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
  }
  node {
    input: "gpu_0/pool2_1"
    input: "gpu_0/pool2_1_scale"
    input: "gpu_0/pool2_1_zero_point"
    output: "gpu_0/pool2_1_Conv_nc_rename_8_QuantizeLinear"
    name: "gpu_0/pool2_1_Conv_nc_rename_8_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/conv3_b_0_quantized"
    input: "gpu_0/conv3_b_0_scale"
    input: "gpu_0/conv3_b_0_zero_point"
    output: "gpu_0/conv3_b_0_dequantized"
    name: "gpu_0/conv3_b_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv3_w_0_quantized"
    input: "gpu_0/conv3_w_0_scale"
    input: "gpu_0/conv3_w_0_zero_point"
    output: "gpu_0/conv3_w_0_dequantized"
    name: "gpu_0/conv3_w_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/pool2_1_Conv_nc_rename_8_QuantizeLinear"
    input: "gpu_0/pool2_1_scale"
    input: "gpu_0/pool2_1_zero_point"
    output: "gpu_0/pool2_1_Conv_nc_rename_8_dequantized"
    name: "gpu_0/pool2_1_Conv_nc_rename_8_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/pool2_1_Conv_nc_rename_8_dequantized"
    input: "gpu_0/conv3_w_0_dequantized"
    input: "gpu_0/conv3_b_0_dequantized"
    output: "gpu_0/conv3_1_QuantizeInput"
    name: "Conv_nc_rename_8_quant"
    op_type: "Conv"
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "gpu_0/conv3_1_QuantizeInput"
    input: "gpu_0/conv3_1_scale"
    input: "gpu_0/conv3_1_zero_point"
    output: "gpu_0/conv3_1_quantized"
    name: "gpu_0/conv3_1_Conv_nc_rename_8_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/conv4_b_0_quantized"
    input: "gpu_0/conv4_b_0_scale"
    input: "gpu_0/conv4_b_0_zero_point"
    output: "gpu_0/conv4_b_0_dequantized"
    name: "gpu_0/conv4_b_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv4_w_0_quantized"
    input: "gpu_0/conv4_w_0_scale"
    input: "gpu_0/conv4_w_0_zero_point"
    output: "gpu_0/conv4_w_0_dequantized"
    name: "gpu_0/conv4_w_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv3_1_quantized"
    input: "gpu_0/conv3_1_scale"
    input: "gpu_0/conv3_1_zero_point"
    output: "gpu_0/conv3_1_Conv_nc_rename_10_dequantized"
    name: "gpu_0/conv3_1_Conv_nc_rename_10_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv3_1_Conv_nc_rename_10_dequantized"
    input: "gpu_0/conv4_w_0_dequantized"
    input: "gpu_0/conv4_b_0_dequantized"
    output: "gpu_0/conv4_1_QuantizeInput"
    name: "Conv_nc_rename_10_quant"
    op_type: "Conv"
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "gpu_0/conv4_1_QuantizeInput"
    input: "gpu_0/conv4_1_scale"
    input: "gpu_0/conv4_1_zero_point"
    output: "gpu_0/conv4_1_quantized"
    name: "gpu_0/conv4_1_Conv_nc_rename_10_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/conv5_b_0_quantized"
    input: "gpu_0/conv5_b_0_scale"
    input: "gpu_0/conv5_b_0_zero_point"
    output: "gpu_0/conv5_b_0_dequantized"
    name: "gpu_0/conv5_b_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv5_w_0_quantized"
    input: "gpu_0/conv5_w_0_scale"
    input: "gpu_0/conv5_w_0_zero_point"
    output: "gpu_0/conv5_w_0_dequantized"
    name: "gpu_0/conv5_w_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv4_1_quantized"
    input: "gpu_0/conv4_1_scale"
    input: "gpu_0/conv4_1_zero_point"
    output: "gpu_0/conv4_1_Conv_nc_rename_12_dequantized"
    name: "gpu_0/conv4_1_Conv_nc_rename_12_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv4_1_Conv_nc_rename_12_dequantized"
    input: "gpu_0/conv5_w_0_dequantized"
    input: "gpu_0/conv5_b_0_dequantized"
    output: "gpu_0/conv5_1_QuantizeInput"
    name: "Conv_nc_rename_12_quant"
    op_type: "Conv"
    attribute {
      name: "pads"
      ints: 1
      ints: 1
      ints: 1
      ints: 1
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 3
      ints: 3
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 1
      ints: 1
      type: INTS
    }
  }
  node {
    input: "gpu_0/conv5_1_QuantizeInput"
    input: "gpu_0/conv5_1_scale"
    input: "gpu_0/conv5_1_zero_point"
    output: "gpu_0/conv5_1_quantized"
    name: "gpu_0/conv5_1_Conv_nc_rename_12_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/conv5_1_quantized"
    input: "gpu_0/conv5_1_scale"
    input: "gpu_0/conv5_1_zero_point"
    output: "gpu_0/conv5_1_MaxPool_nc_rename_14_dequantized"
    name: "gpu_0/conv5_1_MaxPool_nc_rename_14_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/conv5_1_MaxPool_nc_rename_14_dequantized"
    output: "gpu_0/pool5_1_QuantizeInput"
    name: "MaxPool_nc_rename_14_quant"
    op_type: "MaxPool"
    attribute {
      name: "pads"
      ints: 0
      ints: 0
      ints: 0
      ints: 0
      type: INTS
    }
    attribute {
      name: "kernel_shape"
      ints: 2
      ints: 2
      type: INTS
    }
    attribute {
      name: "strides"
      ints: 2
      ints: 2
      type: INTS
    }
  }
  node {
    input: "gpu_0/pool5_1_QuantizeInput"
    input: "gpu_0/conv5_1_scale"
    input: "gpu_0/conv5_1_zero_point"
    output: "gpu_0/pool5_1_quantized"
    name: "gpu_0/pool5_1_MaxPool_nc_rename_14_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/pool5_1_quantized"
    input: "gpu_0/conv5_1_scale"
    input: "gpu_0/conv5_1_zero_point"
    output: "gpu_0/pool5_1_Reshape_nc_rename_15_dequantized"
    name: "gpu_0/pool5_1_Reshape_nc_rename_15_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/pool5_1_Reshape_nc_rename_15_dequantized"
    input: "OC2_DUMMY_1"
    output: "OC2_DUMMY_0_QuantizeInput"
    name: "Reshape_nc_rename_15_quant"
    op_type: "Reshape"
  }
  node {
    input: "OC2_DUMMY_0_QuantizeInput"
    input: "gpu_0/conv5_1_scale"
    input: "gpu_0/conv5_1_zero_point"
    output: "OC2_DUMMY_0_quantized"
    name: "OC2_DUMMY_0_Reshape_nc_rename_15_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/fc6_w_0_quantized"
    input: "gpu_0/fc6_w_0_scale"
    input: "gpu_0/fc6_w_0_zero_point"
    output: "gpu_0/fc6_w_0_dequantized"
    name: "gpu_0/fc6_w_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "OC2_DUMMY_0_quantized"
    input: "gpu_0/conv5_1_scale"
    input: "gpu_0/conv5_1_zero_point"
    output: "OC2_DUMMY_0_MatMul_nc_rename_16_dequantized"
    name: "OC2_DUMMY_0_MatMul_nc_rename_16_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "OC2_DUMMY_0_MatMul_nc_rename_16_dequantized"
    input: "gpu_0/fc6_w_0_dequantized"
    output: "gpu_0/fc6_1_MatMul_QuantizeInput"
    name: "MatMul_nc_rename_16_quant"
    op_type: "MatMul"
  }
  node {
    input: "gpu_0/fc6_1_MatMul_QuantizeInput"
    input: "gpu_0/fc6_1_MatMul_scale"
    input: "gpu_0/fc6_1_MatMul_zero_point"
    output: "gpu_0/fc6_1_MatMul_quantized"
    name: "gpu_0/fc6_1_MatMul_MatMul_nc_rename_16_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/fc6_1_MatMul_quantized"
    input: "gpu_0/fc6_1_MatMul_scale"
    input: "gpu_0/fc6_1_MatMul_zero_point"
    output: "gpu_0/fc6_1_MatMul"
    name: "gpu_0/fc6_1_MatMul_MatMul_nc_rename_16_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/fc6_1_MatMul"
    input: "gpu_0/fc6_b_0"
    output: "gpu_0/fc6_1"
    name: "Add_nc_rename_17"
    op_type: "Add"
  }
  node {
    input: "gpu_0/fc6_1"
    output: "gpu_0/fc6_2"
    name: "Relu_nc_rename_18"
    op_type: "Relu"
  }
  node {
    input: "gpu_0/fc6_2"
    input: "gpu_0/fc6_2_scale"
    input: "gpu_0/fc6_2_zero_point"
    output: "gpu_0/fc6_2_MatMul_nc_rename_19_QuantizeLinear"
    name: "gpu_0/fc6_2_MatMul_nc_rename_19_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/fc7_w_0_quantized"
    input: "gpu_0/fc7_w_0_scale"
    input: "gpu_0/fc7_w_0_zero_point"
    output: "gpu_0/fc7_w_0_dequantized"
    name: "gpu_0/fc7_w_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/fc6_2_MatMul_nc_rename_19_QuantizeLinear"
    input: "gpu_0/fc6_2_scale"
    input: "gpu_0/fc6_2_zero_point"
    output: "gpu_0/fc6_2_MatMul_nc_rename_19_dequantized"
    name: "gpu_0/fc6_2_MatMul_nc_rename_19_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/fc6_2_MatMul_nc_rename_19_dequantized"
    input: "gpu_0/fc7_w_0_dequantized"
    output: "gpu_0/fc7_1_MatMul_QuantizeInput"
    name: "MatMul_nc_rename_19_quant"
    op_type: "MatMul"
  }
  node {
    input: "gpu_0/fc7_1_MatMul_QuantizeInput"
    input: "gpu_0/fc7_1_MatMul_scale"
    input: "gpu_0/fc7_1_MatMul_zero_point"
    output: "gpu_0/fc7_1_MatMul_quantized"
    name: "gpu_0/fc7_1_MatMul_MatMul_nc_rename_19_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/fc7_1_MatMul_quantized"
    input: "gpu_0/fc7_1_MatMul_scale"
    input: "gpu_0/fc7_1_MatMul_zero_point"
    output: "gpu_0/fc7_1_MatMul"
    name: "gpu_0/fc7_1_MatMul_MatMul_nc_rename_19_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/fc7_1_MatMul"
    input: "gpu_0/fc7_b_0"
    output: "gpu_0/fc7_1"
    name: "Add_nc_rename_20"
    op_type: "Add"
  }
  node {
    input: "gpu_0/fc7_1"
    output: "gpu_0/fc7_2"
    name: "Relu_nc_rename_21"
    op_type: "Relu"
  }
  node {
    input: "gpu_0/fc7_2"
    input: "gpu_0/fc7_2_scale"
    input: "gpu_0/fc7_2_zero_point"
    output: "gpu_0/fc7_2_MatMul_nc_rename_22_QuantizeLinear"
    name: "gpu_0/fc7_2_MatMul_nc_rename_22_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/fc8_w_0_quantized"
    input: "gpu_0/fc8_w_0_scale"
    input: "gpu_0/fc8_w_0_zero_point"
    output: "gpu_0/fc8_w_0_dequantized"
    name: "gpu_0/fc8_w_0_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/fc7_2_MatMul_nc_rename_22_QuantizeLinear"
    input: "gpu_0/fc7_2_scale"
    input: "gpu_0/fc7_2_zero_point"
    output: "gpu_0/fc7_2_MatMul_nc_rename_22_dequantized"
    name: "gpu_0/fc7_2_MatMul_nc_rename_22_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/fc7_2_MatMul_nc_rename_22_dequantized"
    input: "gpu_0/fc8_w_0_dequantized"
    output: "gpu_0/pred_1_MatMul_QuantizeInput"
    name: "MatMul_nc_rename_22_quant"
    op_type: "MatMul"
  }
  node {
    input: "gpu_0/pred_1_MatMul_QuantizeInput"
    input: "gpu_0/pred_1_MatMul_scale"
    input: "gpu_0/pred_1_MatMul_zero_point"
    output: "gpu_0/pred_1_MatMul_quantized"
    name: "gpu_0/pred_1_MatMul_MatMul_nc_rename_22_QuantizeLinear"
    op_type: "QuantizeLinear"
  }
  node {
    input: "gpu_0/pred_1_MatMul_quantized"
    input: "gpu_0/pred_1_MatMul_scale"
    input: "gpu_0/pred_1_MatMul_zero_point"
    output: "gpu_0/pred_1_MatMul"
    name: "gpu_0/pred_1_MatMul_MatMul_nc_rename_22_DequantizeLinear"
    op_type: "DequantizeLinear"
  }
  node {
    input: "gpu_0/pred_1_MatMul"
    input: "gpu_0/fc8_b_0"
    output: "gpu_0/pred_1"
    name: "Add_nc_rename_23"
    op_type: "Add"
  }
  node {
    input: "gpu_0/pred_1"
    output: "gpu_0/softmax_1"
    name: "Softmax_nc_rename_24"
    op_type: "Softmax"
  }
  name: "zfnet512"
  initializer {
    dims: 2
    data_type: 7
    name: "OC2_DUMMY_1"
    raw_data: "\001\000\000\000\000\000\000\000\000H\000\000\000\000\000\000"
  }
  initializer {
    data_type: 2
    int32_data: 115
    name: "gpu_0/data_0_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 1.0774157
    name: "gpu_0/data_0_scale"
  }
  initializer {
    data_type: 1
    float_data: 0.0032470974
    name: "gpu_0/conv1_w_0_scale"
  }
  initializer {
    data_type: 3
    int32_data: 0
    name: "gpu_0/conv1_w_0_zero_point"
  }
  initializer {
    data_type: 2
    int32_data: 0
    name: "gpu_0/conv1_1_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 9.183652
    name: "gpu_0/conv1_1_scale"
  }
  initializer {
    dims: 1
    data_type: 1
    name: "gpu_0/conv1_b_0_scale"
    raw_data: "\246Fe;"
  }
  initializer {
    dims: 1
    data_type: 6
    name: "gpu_0/conv1_b_0_zero_point"
    raw_data: "\000\000\000\000"
  }
  initializer {
    data_type: 2
    int32_data: 0
    name: "gpu_0/pool1_1_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 0.20458718
    name: "gpu_0/pool1_1_scale"
  }
  initializer {
    data_type: 1
    float_data: 0.0018832792
    name: "gpu_0/conv2_w_0_scale"
  }
  initializer {
    data_type: 3
    int32_data: 0
    name: "gpu_0/conv2_w_0_zero_point"
  }
  initializer {
    data_type: 2
    int32_data: 0
    name: "gpu_0/conv2_1_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 1.3180004
    name: "gpu_0/conv2_1_scale"
  }
  initializer {
    dims: 1
    data_type: 1
    name: "gpu_0/conv2_b_0_scale"
    raw_data: "d\001\3129"
  }
  initializer {
    dims: 1
    data_type: 6
    name: "gpu_0/conv2_b_0_zero_point"
    raw_data: "\000\000\000\000"
  }
  initializer {
    data_type: 2
    int32_data: 0
    name: "gpu_0/pool2_1_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 0.20458624
    name: "gpu_0/pool2_1_scale"
  }
  initializer {
    data_type: 1
    float_data: 0.00435495
    name: "gpu_0/conv3_w_0_scale"
  }
  initializer {
    data_type: 3
    int32_data: 0
    name: "gpu_0/conv3_w_0_zero_point"
  }
  initializer {
    data_type: 2
    int32_data: 0
    name: "gpu_0/conv3_1_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 0.62580436
    name: "gpu_0/conv3_1_scale"
  }
  initializer {
    dims: 1
    data_type: 1
    name: "gpu_0/conv3_b_0_scale"
    raw_data: "\201\217i:"
  }
  initializer {
    dims: 1
    data_type: 6
    name: "gpu_0/conv3_b_0_zero_point"
    raw_data: "\000\000\000\000"
  }
  initializer {
    data_type: 1
    float_data: 0.00330032
    name: "gpu_0/conv4_w_0_scale"
  }
  initializer {
    data_type: 3
    int32_data: 0
    name: "gpu_0/conv4_w_0_zero_point"
  }
  initializer {
    data_type: 2
    int32_data: 0
    name: "gpu_0/conv4_1_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 0.5981335
    name: "gpu_0/conv4_1_scale"
  }
  initializer {
    dims: 1
    data_type: 1
    name: "gpu_0/conv4_b_0_scale"
    raw_data: "\346Z\007;"
  }
  initializer {
    dims: 1
    data_type: 6
    name: "gpu_0/conv4_b_0_zero_point"
    raw_data: "\000\000\000\000"
  }
  initializer {
    data_type: 1
    float_data: 0.0020665287
    name: "gpu_0/conv5_w_0_scale"
  }
  initializer {
    data_type: 3
    int32_data: 0
    name: "gpu_0/conv5_w_0_zero_point"
  }
  initializer {
    data_type: 2
    int32_data: 0
    name: "gpu_0/conv5_1_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 0.4077084
    name: "gpu_0/conv5_1_scale"
  }
  initializer {
    dims: 1
    data_type: 1
    name: "gpu_0/conv5_b_0_scale"
    raw_data: "K\003\242:"
  }
  initializer {
    dims: 1
    data_type: 6
    name: "gpu_0/conv5_b_0_zero_point"
    raw_data: "\000\000\000\000"
  }
  initializer {
    data_type: 1
    float_data: 0.00045266363
    name: "gpu_0/fc6_w_0_scale"
  }
  initializer {
    data_type: 3
    int32_data: 0
    name: "gpu_0/fc6_w_0_zero_point"
  }
  initializer {
    data_type: 2
    int32_data: 152
    name: "gpu_0/fc6_1_MatMul_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 0.15274827
    name: "gpu_0/fc6_1_MatMul_scale"
  }
  initializer {
    data_type: 2
    int32_data: 0
    name: "gpu_0/fc6_2_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 0.061371975
    name: "gpu_0/fc6_2_scale"
  }
  initializer {
    data_type: 1
    float_data: 0.0005497247
    name: "gpu_0/fc7_w_0_scale"
  }
  initializer {
    data_type: 3
    int32_data: 0
    name: "gpu_0/fc7_w_0_zero_point"
  }
  initializer {
    data_type: 2
    int32_data: 103
    name: "gpu_0/fc7_1_MatMul_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 0.064987786
    name: "gpu_0/fc7_1_MatMul_scale"
  }
  initializer {
    data_type: 2
    int32_data: 0
    name: "gpu_0/fc7_2_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 0.039591193
    name: "gpu_0/fc7_2_scale"
  }
  initializer {
    data_type: 1
    float_data: 0.0007954131
    name: "gpu_0/fc8_w_0_scale"
  }
  initializer {
    data_type: 3
    int32_data: 0
    name: "gpu_0/fc8_w_0_zero_point"
  }
  initializer {
    data_type: 2
    int32_data: 64
    name: "gpu_0/pred_1_MatMul_zero_point"
  }
  initializer {
    data_type: 1
    float_data: 0.13262747
    name: "gpu_0/pred_1_MatMul_scale"
  }
  input {
    name: "gpu_0/data_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 224
          }
          dim {
            dim_value: 224
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/fc6_b_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/fc7_b_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/fc8_b_0"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1000
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/conv1_w_0_quantized"
    type {
      tensor_type {
        elem_type: 3
        shape {
          dim {
            dim_value: 96
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 7
          }
          dim {
            dim_value: 7
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/conv1_b_0_quantized"
    type {
      tensor_type {
        elem_type: 6
        shape {
          dim {
            dim_value: 96
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/conv2_w_0_quantized"
    type {
      tensor_type {
        elem_type: 3
        shape {
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 96
          }
          dim {
            dim_value: 5
          }
          dim {
            dim_value: 5
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/conv2_b_0_quantized"
    type {
      tensor_type {
        elem_type: 6
        shape {
          dim {
            dim_value: 256
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/conv3_w_0_quantized"
    type {
      tensor_type {
        elem_type: 3
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/conv3_b_0_quantized"
    type {
      tensor_type {
        elem_type: 6
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/conv4_w_0_quantized"
    type {
      tensor_type {
        elem_type: 3
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/conv4_b_0_quantized"
    type {
      tensor_type {
        elem_type: 6
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/conv5_w_0_quantized"
    type {
      tensor_type {
        elem_type: 3
        shape {
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 512
          }
          dim {
            dim_value: 3
          }
          dim {
            dim_value: 3
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/conv5_b_0_quantized"
    type {
      tensor_type {
        elem_type: 6
        shape {
          dim {
            dim_value: 512
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/fc6_w_0_quantized"
    type {
      tensor_type {
        elem_type: 3
        shape {
          dim {
            dim_value: 18432
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/fc7_w_0_quantized"
    type {
      tensor_type {
        elem_type: 3
        shape {
          dim {
            dim_value: 4096
          }
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  input {
    name: "gpu_0/fc8_w_0_quantized"
    type {
      tensor_type {
        elem_type: 3
        shape {
          dim {
            dim_value: 1024
          }
          dim {
            dim_value: 1000
          }
        }
      }
    }
  }
  output {
    name: "gpu_0/softmax_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1000
          }
        }
      }
    }
  }
  value_info {
    name: "OC2_DUMMY_1"
    type {
      tensor_type {
        elem_type: 7
        shape {
          dim {
            dim_value: 2
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/data_0_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/data_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv1_w_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv1_w_0_zero_point"
    type {
      tensor_type {
        elem_type: 3
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv1_1_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv1_1_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv1_b_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv1_b_0_zero_point"
    type {
      tensor_type {
        elem_type: 6
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/pool1_1_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/pool1_1_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv2_w_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv2_w_0_zero_point"
    type {
      tensor_type {
        elem_type: 3
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv2_1_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv2_1_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv2_b_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv2_b_0_zero_point"
    type {
      tensor_type {
        elem_type: 6
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/pool2_1_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/pool2_1_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv3_w_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv3_w_0_zero_point"
    type {
      tensor_type {
        elem_type: 3
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv3_1_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv3_1_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv3_b_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv3_b_0_zero_point"
    type {
      tensor_type {
        elem_type: 6
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv4_w_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv4_w_0_zero_point"
    type {
      tensor_type {
        elem_type: 3
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv4_1_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv4_1_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv4_b_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv4_b_0_zero_point"
    type {
      tensor_type {
        elem_type: 6
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv5_w_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv5_w_0_zero_point"
    type {
      tensor_type {
        elem_type: 3
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv5_1_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv5_1_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv5_b_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv5_b_0_zero_point"
    type {
      tensor_type {
        elem_type: 6
        shape {
          dim {
            dim_value: 1
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc6_w_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc6_w_0_zero_point"
    type {
      tensor_type {
        elem_type: 3
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc6_1_MatMul_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc6_1_MatMul_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc6_2_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc6_2_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc7_w_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc7_w_0_zero_point"
    type {
      tensor_type {
        elem_type: 3
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc7_1_MatMul_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc7_1_MatMul_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc7_2_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc7_2_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc8_w_0_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc8_w_0_zero_point"
    type {
      tensor_type {
        elem_type: 3
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/pred_1_MatMul_zero_point"
    type {
      tensor_type {
        elem_type: 2
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/pred_1_MatMul_scale"
    type {
      tensor_type {
        elem_type: 1
        shape {
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv1_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 96
          }
          dim {
            dim_value: 109
          }
          dim {
            dim_value: 109
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/norm1_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 96
          }
          dim {
            dim_value: 109
          }
          dim {
            dim_value: 109
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/pool1_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 96
          }
          dim {
            dim_value: 54
          }
          dim {
            dim_value: 54
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/conv2_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 25
          }
          dim {
            dim_value: 25
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/norm2_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 25
          }
          dim {
            dim_value: 25
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/pool2_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 256
          }
          dim {
            dim_value: 12
          }
          dim {
            dim_value: 12
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc6_1_MatMul"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc6_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc6_2"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 4096
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc7_1_MatMul"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc7_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/fc7_2"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1024
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/pred_1_MatMul"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1000
          }
        }
      }
    }
  }
  value_info {
    name: "gpu_0/pred_1"
    type {
      tensor_type {
        elem_type: 1
        shape {
          dim {
            dim_value: 1
          }
          dim {
            dim_value: 1000
          }
        }
      }
    }
  }
}
opset_import {
  domain: ""
  version: 12
}
